### ISSUE TITLE
Converting DuStrokes to DuShapes

### ISSUE THREAD

**Issue by jetrotal** [Rainbox-dev/DuStroke#4]
I just saw a taper preset made by School of Motion:
![image](https://user-images.githubusercontent.com/45118493/63885007-beda1800-c9ad-11e9-89b2-3b81f0f6daaa.png)
https://www.schoolofmotion.com/tutorials/free-tapered-stroke-after-effects/

It's basically a group of strokes with different thickness stretched inside a path.

That gave me the idea of doing the same with any shape object, through Satoru Yonekura's shapeOnPath expressions.

![image](https://user-images.githubusercontent.com/45118493/63884675-0318e880-c9ad-11e9-8608-6e0f150f7dfa.png)

That could give us a powerful (and probably slower) variation of DuStroke, that can distort and stretch multiple brushes, instead of just placing and transforming them.

![Comp_Shape_on_path](https://user-images.githubusercontent.com/45118493/63900207-358b0b80-c9d6-11e9-8c67-b38a9bd5c058.gif)
_part of a DuStroke brush, converted to Shape Layer, then duplicated two times along a path._

We could even make use of the "Create Shape from Text" command to convert DuStroke's brushes to this format.

![image](https://user-images.githubusercontent.com/45118493/63885738-6146cb00-c9af-11e9-8685-29d978a8915b.png)

And so, <rd> brushes could have tons of hold-keyframes that cycles through different brushes...

**Comment by Nico-Duduf** [comment]
I'm not sure it could be very useful, compared to the loss in performance this would imply. Lots of expressions on paths
Going too far with the tool would just make it too complicated just for enabling very specific features.
A LOT of stuff can always be done, but it's important to balance what is really useful for the users (not just for us who know the thing very well), and how to keep it accessible, intuitive, and with not-too-poor performance.

**Comment by jetrotal** [comment]
You are right on this one. Seemed a good idea at first.
I will close this Issue.
